jobs:
  - script: >
      pipelineJob('maven-pipeline-version-controlled') {
          definition {
              triggers {
                  cron('H/5 * * * *')
              }
              cpsScm {
                  scm {
                    git {
                        remote { url 'https://github.com/tsundberg/maven-build-with-jenkins-pipeline.git' }
                        branch '*/master'
                        extensions {}
                    }
                  }
                  scriptPath 'src/ci/Jenkinsfile'
              }
          }
      }